import { api } from './api';

import { FormValues } from '@shared';
// LLM session generation runs a reasoning model server-side and routinely takes
// far longer than the api client's default 15s timeout — without this override
// the mobile client aborts with a timeout error while the backend completes and
// saves the plan (the user then sees an error on a session that did generate).
const PLAN_GEN_TIMEOUT_MS = 120000;

export interface NextSessionExercise {
  name: string;
  sets: number;
  reps: number;
  weight: number;
  rpe?: number;
  weightPerc?: number;
  cue?: string;
}

/** Schedule + big-3 frequency the coach infers from recent logged sessions. */
export interface SuggestedConstraints {
  trainingDays: string[] | null;
  sessionsPerWeek: number | null;
  avgSessionMinutes: number | null;
  squatFrequencyPerWeek: number | null;
  benchFrequencyPerWeek: number | null;
  deadliftFrequencyPerWeek: number | null;
  sessionCount: number;
}

export interface NextSession {
  focus: string;
  exercises: NextSessionExercise[];
  /** 3-sentence coach rationale: key insight, why this load/focus, what to watch. */
  coachsCall?: string;
}

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

export interface CoachPreferences {
  timeSlot: 'morning' | 'afternoon' | 'evening';
  duration: number;
  intensity: number;
}

export type FatigueLevel = 'none' | 'mild' | 'elevated' | 'high';

export interface FatigueStatus {
  requiresAck: boolean;
  level: FatigueLevel;
  reasons: string[];
  /** True while an "I feel fine" dismissal is live (until the next logged session). */
  dismissed: boolean;
  /** The athlete may clear this alarm (elevated/high, not dismissed, not a scheduled deload). */
  canDismiss: boolean;
  /** This is a programmed deload week — planned recovery, not a reactive flag. */
  scheduledDeload: boolean;
  /** What the coach wants done about it — 'taper' when a max attempt is close enough
   *  that a deload would clear the fatigue but leave the athlete flat for it. */
  recommendation: FatigueRecommendation | null;
}

export interface FatigueRecommendation {
  action: 'taper' | 'deload' | 'trim';
  peak: { kind: 'competition' | 'pr_test' | 'block_peak'; daysAway: number | null; label: string } | null;
  headline: string;
  detail: string;
}

/** Mirrors backend pr-forecast.ts. See that module for what each verdict promises. */
export type PrVerdict = 'primed' | 'on_track' | 'hold' | 'not_today' | 'deferred' | 'insufficient_data';

export interface PrDriver {
  key: string;
  direction: 'positive' | 'negative' | 'neutral';
  detail: string;
}

export interface PrLiftForecast {
  lift: 'squat' | 'bench' | 'deadlift';
  label: string;
  verdict: PrVerdict;
  /** Best logged single — the number a true PR has to beat. */
  record: number | null;
  /** What the current block's sets project a top single at. */
  projectedTop: number | null;
  marginPct: number | null;
  /** The cheaper record: a triple that would also stand. */
  triple: { record: number | null; projected: number | null } | null;
  confidence: 'high' | 'medium' | 'low';
  drivers: PrDriver[];
  headline: string;
  detail: string;
  /** ISO date a deferred attempt lands on (taper windows only). */
  attemptWindow: string | null;
  /** Whether a single or triple is actually programmed — only those can set a record. */
  attemptScheduled: boolean;
  sessionsInBlock: number;
}

export interface PrForecast {
  lifts: PrLiftForecast[];
  /** The lift closest to a record — what the single-card UI shows. */
  best: PrLiftForecast | null;
  /** Set when the feature is deliberately silent (hypertrophy athletes never max). */
  suppressed: 'hypertrophy' | null;
  generatedAt: string;
}

export interface CoachNote {
  id: string;
  category: string;
  description: string;
  exerciseName: string | null;
  autoGenerated: boolean;
  createdAt: string;
}

export type PathTier = 'novice' | 'beginner' | 'intermediate' | 'advanced';
export type PathBranchId = 'muscle' | 'powerbuilding' | 'strength';
export type PathNodeState = 'completed' | 'current' | 'available' | 'locked';

export interface PathTierNode {
  tier: PathTier;
  label: string;
  state: PathNodeState;
}

export interface PathBranch {
  id: PathBranchId;
  label: string;
  icon: string;
  isCurrent: boolean;
  tiers: PathTierNode[];
}

export interface PathMilestone {
  id: string;
  label: string;
  description: string;
  icon: string;
  kind: 'consistency' | 'strength';
  achieved: boolean;
  progress: number;
  current: number;
  target: number;
  unit: string;
}

export interface PathTree {
  currentBranchId: PathBranchId;
  currentTier: PathTier;
  foundation: PathNodeState;
  branches: PathBranch[];
  milestones: PathMilestone[];
  nextMilestones: PathMilestone[];
}

export interface AICoachProfileData {
  primaryGoal?: string;
  specificGoal?: string;
  timeline?: string;
  priorityHierarchy?: string;
  successMetrics?: string;
  yearsTraining?: number;
  experienceLevel?: 'novice' | 'beginner' | 'intermediate' | 'advanced';
  bestSystems?: string[];
  failedSystems?: string[];
  adaptationSpeed?: string;
  squatMax?: number;
  benchMax?: number;
  deadliftMax?: number;
  squatERM?: number;
  benchERM?: number;
  deadliftERM?: number;
  prTrend?: string;
  squatWeakPoint?: string;
  benchWeakPoint?: string;
  deadliftWeakPoint?: string;
  mobilityLimitations?: string[];
  preferredSquatStance?: string;
  avgSleepHours?: number;
  sleepQuality?: string;
  jobStressLevel?: number;
  physicalLabor?: boolean;
  weeklyCardioSessions?: number;
  otherSports?: string[];
  otherSportsFrequency?: string;
  injuryHistory?: string;
  recoverySpeed?: string;
  trainingDaysPerWeek?: number;
  trainingDays?: string[];
  sessionDurationMinutes?: number;
  equipmentAccess?: string;
  minPlateKg?: number; // smallest plate per side (kg): 0.25 | 0.5 | 1 | 1.25 | 2.5
  responseType?: string;
  deadliftRecoveryCost?: string;
  painfulExercises?: string;
  preferredExercises?: string;
  currentPhase?: string;
  dailyProteinTarget?: number;
  weightClassTarget?: string;
  prefersStructure?: boolean;
  missedLiftResponse?: string;
  overshootsEffort?: boolean;
  motivationConsistency?: string;
  trackingHabits?: string[];
  preferredPeakingStyle?: string;
  meetExperience?: number;
  deloadResponse?: string;
  taperSensitivity?: string;
  historicalWorkoutData?: string;
  squatFrequencyPerWeek?: number;
  benchFrequencyPerWeek?: number;
  deadliftFrequencyPerWeek?: number;
  nutritionTrackingEnabled?: boolean;
  trainingFocus?: string; // 'hypertrophy' | 'powerbuilding' | 'strength'
  preferredIntensity?: number; // 1=Easy 2=Light 3=Moderate 4=Hard 5=Max
}

export interface RecoveryWeekStatus {
  // 'taper' is the one mode that is NOT a deload — volume down, intensity held.
  mode: 'recovery' | 'vacation' | 'taper';
  until: string; // YYYY-MM-DD — the day hard training resumes (taper: the peak day)
  resumeWeek: number | null; // phase week that replays on return (null in comp prep)
}

export const aiCoachService = {
  chat: async (
    message: string,
    history: ChatMessage[],
    preferences?: CoachPreferences,
  ): Promise<string> => {
    const { data } = await api.post<{ data: { reply: string } }>('/ai-coach/chat', {
      message,
      history,
      preferences,
    });
    return data.data.reply;
  },

  saveProfile: async (profileData: AICoachProfileData): Promise<void> => {
    await api.post('/ai-coach/profile', profileData);
  },

  getProfile: async (): Promise<AICoachProfileData | null> => {
    const { data } = await api.get<{ data: AICoachProfileData | null }>('/ai-coach/profile');
    return data.data;
  },

  generatePlan: async (readiness?: { mood?: string; energyLevel?: number; sleepHours?: number }, note?: string, makeUp?: boolean, skipNext?: boolean, fatigueDecision?: 'accept' | 'dismiss'): Promise<string> => {
    const { data } = await api.post<{ data: { plan: string } }>('/ai-coach/generate-plan', { ...readiness ?? {}, ...(note ? { note } : {}), ...(makeUp ? { makeUp: true } : {}), ...(skipNext ? { skipNext: true } : {}), ...(fatigueDecision ? { fatigueDecision } : {}) }, { timeout: PLAN_GEN_TIMEOUT_MS });
    return data.data.plan;
  },

  /**
   * Cheap, LLM-free readiness gate. Call after the readiness check and before
   * generatePlan: if `requiresAck`, surface `reasons` and let the athlete choose
   * recovery ('accept') or "I feel fine" ('dismiss'), then pass that into generatePlan.
   */
  fatigueCheck: async (): Promise<FatigueStatus> => {
    const { data } = await api.get<{ data: FatigueStatus }>('/ai-coach/fatigue-check');
    return data.data;
  },

  /**
   * "Is a PR on?" — deterministic, LLM-free and unmetered, so it can be called on
   * every screen entry. Read-only: nothing here changes a prescribed load.
   */
  prForecast: async (): Promise<PrForecast> => {
    const { data } = await api.get<{ data: PrForecast }>('/ai-coach/pr-forecast');
    return data.data;
  },

  /** "I feel fine, clear it" — dismiss a reactive fatigue alarm. Live until the next logged session. */
  dismissFatigue: async (): Promise<FatigueStatus> => {
    const { data } = await api.post<{ data: FatigueStatus }>('/ai-coach/fatigue-dismiss');
    return data.data;
  },

  /** Undo a dismissal — opt back into recovery. */
  resumeFatigue: async (): Promise<FatigueStatus> => {
    const { data } = await api.post<{ data: FatigueStatus }>('/ai-coach/fatigue-resume');
    return data.data;
  },

  /** Add a free-form "remember this about me" note; backend reformats it into a clean coaching note. */
  addNote: async (text: string): Promise<CoachNote> => {
    const { data } = await api.post<{ data: CoachNote }>('/ai-coach/note', { text });
    return data.data;
  },

  /** The athlete's active coaching notes (self-authored + coach-observed). */
  getNotes: async (): Promise<CoachNote[]> => {
    const { data } = await api.get<{ data: CoachNote[] }>('/ai-coach/notes');
    return data.data;
  },

  deleteNote: async (id: string): Promise<void> => {
    await api.delete(`/ai-coach/note/${id}`);
  },

  /** Fire-and-forget: runs full intelligence analysis then generates next plan */
  postSession: async (sessionId: string): Promise<void> => {
    await api.post(`/ai-coach/post-session/${sessionId}`);
  },

  // `language` is the English name of the target language (e.g. "Bosnian"),
  // matching LANGUAGES[].aiName so the backend can instruct the model directly.
  generateShareCaption: async (
    sessionId: string,
    language: string,
    overrides?: { notes?: string; mood?: string },
  ): Promise<{ hype: string; clean: string; funny: string }> => {
    const { data } = await api.post<{ data: { hype: string; clean: string; funny: string } }>(
      `/ai-coach/share-caption/${sessionId}`,
      { language, ...overrides },
    );
    return data.data;
  },

  getDebugPrompt: async (): Promise<{ systemPrompt: string; userMessage: string; layers: Record<string, string | null> }> => {
    const { data } = await api.get<{ data: { systemPrompt: string; userMessage: string; layers: Record<string, string | null> } }>('/ai-coach/debug-prompt');
    return data.data;
  },

  getPlan: async (): Promise<{
    plan: string | null;
    generatedAt: string | null;
    nextSessionJson: NextSession | null;
    trainingDays: string[] | null;
    competitionDate: string | null;
    competitionType: string | null;
    injuryHandling: string | null;
    activeInjuries: { id: string; exerciseName: string | null; description: string }[];
    trainingWeek: number | null;
    sessionInWeek: number | null;
    sessionsPerCycle: number | null;
    missedSession: { day: string; lifts: string[] } | null;
    catchUpRecommendation: 'make_up' | 'skip' | null;
    nextScheduledDay: string | null;
    skipAheadDay: string | null;
    completedToday: boolean;
    regenerating: boolean;
    recoveryWeek: RecoveryWeekStatus | null;
  }> => {
    const { data } = await api.get<{ data: {
      plan: string | null;
      generatedAt: string | null;
      nextSessionJson: NextSession | null;
      trainingDays: string[] | null;
      competitionDate: string | null;
      competitionType: string | null;
      injuryHandling: string | null;
      activeInjuries: { id: string; exerciseName: string | null; description: string }[];
      trainingWeek: number | null;
      sessionInWeek: number | null;
      sessionsPerCycle: number | null;
      missedSession: { day: string; lifts: string[] } | null;
      catchUpRecommendation: 'make_up' | 'skip' | null;
      nextScheduledDay: string | null;
      skipAheadDay: string | null;
      completedToday: boolean;
      regenerating: boolean;
      recoveryWeek: RecoveryWeekStatus | null;
    } }>('/ai-coach/plan');
    return data.data;
  },

  /**
   * "Life fell apart" reset, or a peak-preserving unload. 'recovery' turns the rest of
   * this week into light deload sessions and replays the interrupted phase week from
   * Monday; 'vacation' pauses the plan for `days` days (no logging expected, no make-up
   * debt) and replays on return; 'taper' cuts volume for a few days while HOLDING load
   * so the peak week lands at the end of the window instead of being trained tired.
   * Omit `days` to let each mode apply its own default.
   */
  triggerRecoveryWeek: async (mode: 'recovery' | 'vacation' | 'taper', days?: number): Promise<{
    until: string;
    resumePhase: string;
    resumeWeek: number | null;
    mode: 'recovery' | 'vacation' | 'taper';
    compCountdownContinues: boolean;
    fatigueWarning: string | null;
  }> => {
    const { data } = await api.post<{ data: { until: string; resumePhase: string; resumeWeek: number | null; mode: 'recovery' | 'vacation' | 'taper'; compCountdownContinues: boolean; fatigueWarning: string | null } }>(
      '/ai-coach/recovery-week',
      { mode, ...(days ? { days } : {}) },
    );
    return data.data;
  },

  cancelRecoveryWeek: async (): Promise<void> => {
    await api.delete('/ai-coach/recovery-week');
  },

  getPathTree: async (): Promise<PathTree> => {
    const { data } = await api.get<{ data: PathTree }>('/ai-coach/path-tree');
    return data.data;
  },

  setInjuryPreference: async (handling: 'replace' | 'remove' | 'reduce'): Promise<void> => {
    await api.post('/ai-coach/injury-preference', { handling });
  },

  getSuggestedConstraints: async (): Promise<SuggestedConstraints | null> => {
    try {
      const { data } = await api.get<{ data: SuggestedConstraints }>('/ai-coach/suggested-constraints');
      return data.data;
    } catch {
      return null;
    }
  },

  saveTrainingDays: async (days: string[]): Promise<void> => {
    await api.post('/ai-coach/profile', { trainingDays: days });
  },

  setCompetitionDate: async (date: string, type: 'meet' | 'pr_test'): Promise<void> => {
    await api.post('/ai-coach/competition', { date, type });
  },

  clearCompetitionDate: async (): Promise<void> => {
    await api.delete('/ai-coach/competition');
  },

  getNutritionAdvice: async (): Promise<{ advice: string; generatedAt: string | null }> => {
    const { data } = await api.get<{ data: { advice: string; generatedAt: string | null } }>('/ai-coach/nutrition-advice');
    return data.data;
  },

  setNutritionTracking: async (enabled: boolean): Promise<void> => {
    await api.post('/ai-coach/profile', { nutritionTrackingEnabled: enabled });
  },
};

// ── Admin Lab API ──────────────────────────────────────────────────────────

export interface AdminUserEntry {
  id: string;
  email: string;
  name: string;
  role: string;
  hasAIProfile: boolean;
  totalSessions: number;
}

export interface AdminUserState {
  userId: string;
  phase: string | null;
  weekInPhase: number;
  totalWeeks: number;
  phaseStartedAt: string | null;
  extensionWeeks: number;
  cycleSlot: number;
  totalSessions: number;
  testCycleSlotOffset: number;
  fatigueOverride: string | null;
  fatigueReal: string;
  fatigueEvidence: string[];
  /** Exactly what GET /ai-coach/fatigue-check returns for this user — i.e. the level
   *  the athlete is shown on the plan banner + readiness gate, override applied. */
  fatigueAthlete: {
    level: string;
    dismissed: boolean;
    scheduledDeload: boolean;
    requiresAck: boolean;
    reasons: string[];
  };
  /** Exactly what GET /ai-coach/pr-forecast returns for this user. */
  prForecast: PrForecast;
  /** How often past forecasts matched what the bar did. */
  prForecastAccuracy: {
    tested: number;
    correct: number;
    accuracyPct: number | null;
    open: number;
    unattempted: number;
  };
  memoryLength: number;
  memoryArchiveLength: number;
  activeNotesCount: number;
  exerciseIntelCount: number;
  planRateLimitCount: number;
  planRateLimitMax: number;
  trainingDays: string[] | null;
  squatFreq: number | null;
  benchFreq: number | null;
  deadliftFreq: number | null;
  nextSessionJson: NextSession | null;
  planGeneratedAt: string | null;
}

export const adminAiService = {
  getUsers: async (): Promise<AdminUserEntry[]> => {
    const { data } = await api.get<{ data: AdminUserEntry[] }>('/ai-coach/admin/lab/users');
    return data.data;
  },

  getState: async (userId: string): Promise<AdminUserState> => {
    const { data } = await api.get<{ data: AdminUserState }>(`/ai-coach/admin/lab/${userId}/state`);
    return data.data;
  },

  setPhase: async (userId: string, phase: string, weeksIntoPhase: number): Promise<void> => {
    await api.post(`/ai-coach/admin/lab/${userId}/set-phase`, { phase, weeksIntoPhase });
  },

  setCycleSlot: async (userId: string, offset: number): Promise<void> => {
    await api.post(`/ai-coach/admin/lab/${userId}/set-cycle-slot`, { offset });
  },

  setFatigue: async (userId: string, level: string | null): Promise<void> => {
    await api.post(`/ai-coach/admin/lab/${userId}/set-fatigue`, { level });
  },

  resetRateLimit: async (userId: string): Promise<void> => {
    await api.post(`/ai-coach/admin/lab/${userId}/reset-rate-limit`, {});
  },

  forceGeneratePlan: async (userId: string): Promise<string> => {
    const { data } = await api.post<{ data: { plan: string } }>(`/ai-coach/admin/lab/${userId}/force-generate-plan`, {}, { timeout: PLAN_GEN_TIMEOUT_MS });
    return data.data.plan;
  },

  clearMemory: async (userId: string, clearNotes: boolean, clearExerciseIntel: boolean): Promise<void> => {
    await api.post(`/ai-coach/admin/lab/${userId}/clear-memory`, { clearNotes, clearExerciseIntel });
  },
  clearSessions: async (userId: string): Promise<{ deletedSessions: number }> => {
    const { data } = await api.post<{ data: { deletedSessions: number } }>(`/ai-coach/admin/lab/${userId}/clear-sessions`, {});
    return data.data;
  },

  resetProfile: async (userId: string): Promise<{ deletedSessions: number }> => {
    const { data } = await api.post<{ data: { deletedSessions: number } }>(`/ai-coach/admin/lab/${userId}/reset-profile`, {});
    return data.data;
  },

  setErm: async (userId: string, updates: {
    squatERM?: number; benchERM?: number; deadliftERM?: number;
    squatMax?: number; benchMax?: number; deadliftMax?: number;
  }): Promise<void> => {
    await api.post(`/ai-coach/admin/lab/${userId}/set-erm`, updates);
  },

  getDebugPrompt: async (userId: string): Promise<{ systemPrompt: string; userMessage: string; layers: Record<string, string | null> }> => {
    const { data } = await api.get<{ data: { systemPrompt: string; userMessage: string; layers: Record<string, string | null> } }>(`/ai-coach/admin/lab/${userId}/debug-prompt`);
    return data.data;
  },

  // The editable source profile behind the context message. Numeric columns are
  // returned as strings (see backend getProfile projection), arrays/booleans as-is.
  getProfile: async (userId: string): Promise<FormValues | null> => {
    const { data } = await api.get<{ data: FormValues | null }>(`/ai-coach/admin/lab/${userId}/profile`);
    return data.data;
  },

  saveProfile: async (userId: string, updates: FormValues): Promise<void> => {
    await api.post(`/ai-coach/admin/lab/${userId}/profile`, updates);
  },
};
