import React, { useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, ActivityIndicator, Modal, TextInput } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { palette } from '../../../theme';
import { CoachNote } from '../../../services/ai-coach.service';
import { fat } from './planSheet.styles';

/**
 * Coach memory: notes the athlete asks the coach to remember.
 *
 * Split out of AICoachPlanScreen (2026-10-06, a move with no behaviour change).
 */

// ─── Coach notes ("remember this about me") ───────────────────────────────────

export const NotesModal: React.FC<{
  visible: boolean;
  notes: CoachNote[];
  busy: boolean;
  onAdd: (text: string) => void;
  onDelete: (id: string) => void;
  onClose: () => void;
}> = ({ visible, notes, busy, onAdd, onDelete, onClose }) => {
  const [text, setText] = useState('');
  const submit = () => {
    const trimmed = text.trim();
    if (trimmed.length < 2) return;
    onAdd(trimmed);
    setText('');
  };
  return (
    <Modal visible={visible} animationType="slide" onRequestClose={onClose} presentationStyle="pageSheet">
      <SafeAreaView style={fat.container} edges={['top']}>
        <View style={fat.header}>
          <Text style={fat.title}>Coach memory</Text>
          <TouchableOpacity style={fat.closeBtn} onPress={onClose} accessibilityRole="button" accessibilityLabel="Close">
            <Text style={fat.closeText}>✕</Text>
          </TouchableOpacity>
        </View>
        <ScrollView style={fat.scroll} contentContainerStyle={{ padding: 16 }} keyboardShouldPersistTaps="handled">
          <Text style={fat.intro}>Tell your coach anything worth remembering — how you like to train, what to avoid, a niggle. Write it however you want; I'll save it in my own words.</Text>

          <View style={fat.noteInputRow}>
            <TextInput
              style={fat.noteInput}
              placeholder='e.g. "big weights feel good for me"'
              placeholderTextColor={palette.gray[600]}
              value={text}
              onChangeText={setText}
              maxLength={500}
              multiline
              returnKeyType="done"
              blurOnSubmit
              onSubmitEditing={submit}
            />
            <TouchableOpacity accessibilityRole="button" style={[fat.noteAddBtn, (busy || text.trim().length < 2) && fat.noteAddBtnDisabled]} onPress={submit} disabled={busy || text.trim().length < 2}>
              {busy ? <ActivityIndicator color={palette.white} /> : <Text style={fat.noteAddBtnText}>Save</Text>}
            </TouchableOpacity>
          </View>

          {notes.length > 0 && <Text style={fat.sectionLabel}>What I'm remembering</Text>}
          {notes.map((n) => (
            <View key={n.id} style={fat.noteCard}>
              <View style={{ flex: 1 }}>
                <Text style={fat.noteCat}>{n.category.replace(/_/g, ' ')}{n.exerciseName ? ` · ${n.exerciseName}` : ''}{n.autoGenerated ? ' · observed' : ''}</Text>
                <Text style={fat.noteDesc}>{n.description}</Text>
              </View>
              <TouchableOpacity style={fat.noteDelBtn} onPress={() => onDelete(n.id)} accessibilityRole="button" accessibilityLabel={`Delete note: ${n.description}`}>
                <Text style={fat.noteDelText}>✕</Text>
              </TouchableOpacity>
            </View>
          ))}
          {notes.length === 0 && <Text style={fat.emptyNote}>Nothing saved yet.</Text>}
        </ScrollView>
      </SafeAreaView>
    </Modal>
  );
};
